### ISSUE TITLE
Link to expire after few seconds instead of hour(s)

### ISSUE THREAD

**Issue by MickaelTH** [dreamonkey/laravel-cloudfront-url-signer#18]
Hi,

Trying to get the sign url to expire after few seconds or minutes seems to not be working properly - on my side at least.

When I try:

```CloudFrontUrlSigner::sign('https://myapp.com/resource', now()->addSeconds(10) );```

The url generated is still working even after few minutes. Could it be because of cache in Cloudfront or that we cannot set less than 1 hour?

Also I read that you are not using this package anymore, but it is still maintained ? I saw an update for Laravel 8 so I hope so.

Thanks

**Comment by IlCallo** [comment]
Hello there,
don't really know what could prevent you to set an expiration just some seconds/minutes in the future, everything is converted to a timestamp internally so it shouldn't matter. I don't know about a minimum time set by Cloudfront

This is a really lightweight wrapper around the official `\Aws\CloudFront\UrlSigner` and it's `getSignedUrl($url, $expiration)` method, have you tried searching in their issues too?

If you want to check what is being provided to the underlying signer, just add a `Log::debug` of [this line](https://github.com/dreamonkey/laravel-cloudfront-url-signer/blob/7c486430542510c6957d8455febc3395ed1cac45/src/CloudFrontUrlSigner.php#L78) and see if the printed timestamp corresponds

We don't actively maintain it ourselves, but we gladly accept PRs to advance Laravel major versions support

**Comment by MickaelTH** [comment]
@IlCallo  Thank you for you prompt reply.

I don't understand (yet) why the link is not expiring, but I will check further more and post my findings if any.

**Comment by MickaelTH** [comment]
Closing now as this seems to be because of Chrome caching files, false alert.

Thank you for the prompt reply again!

**Comment by IlCallo** [comment]
No problem, glad you figured it out!
