### ISSUE TITLE
custon path

### ISSUE THREAD

**Issue by matiasmanuelparra** [dreamonkey/laravel-cloudfront-url-signer#27]
The issue is how I change the location of the pem file and place it in the variable CLOUDFRONT_PRIVATE_KEY_PATH. by default this /app/api/storage/file.pem
the idea is to have the pem file in another location .

**Comment by IlCallo** [comment]
`CLOUDFRONT_PRIVATE_KEY_PATH`, as you could guess by the usage of `env()`, is an environment variable you should set into your `.env` file (as all other env variables)

You could just remove `storage_path`, `env`, etc and just provide the hardcoded path to the key
Check out `storage_path` helper [here](https://laravel.com/docs/8.x/helpers#method-storage-path)
