### ISSUE TITLE
V4 Issue

### ISSUE THREAD

**Issue by michaellwatson** [dreamonkey/laravel-cloudfront-url-signer#5]
Signing the URL seems to be working but when I visit the generated URL I get this message:

*Query-string authentication requires the Signature, Expires and AWSAccessKeyId parameters*

If I change the querystring variable Key-Pair-Id to AWSAccessKeyId, I get a different error

*The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.*

Online it says something about this error is related to using v4

Any help you could give would be much appreciated

**Comment by michaellwatson** [comment]
My problem was calling the signer on the bucket url, it should be called on the cloudfront url, with the bucket path removed also, once I did this it was working good.

**Comment by cypherinc** [comment]
@michaellwatson Hi, I am displaying a resource like this, is it correct according to your answer?
`{{CloudFrontUrlSigner::sign(env('AWS_ACCESS_URL_PREFIX').$project->creator->company_slug.'/'.$project->icon)}}`

**Comment by michaellwatson** [comment]
@cypherinc are you calling the signer on the cloudfront url? something like cloudfront.12345.com/filename

**Comment by owenconti** [comment]
@cypherinc This is how we do it:

First, make sure you have your s3 disk configured in `filesystems.php`:

```
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],
    ],
```

Then when signing, create the path via Laravel:

```
$url = Storage::disk('s3')->url('/slug/icon-example');
return CloudFrontUrlSigner::sign($url);
```

**Comment by michaellwatson** [comment]
@cypherinc 
`$url =$cloudfront_url->url('/slug/icon-example');`
worked for me, been a while since I used it tho

**Comment by cypherinc** [comment]
@michaellwatson @owenconti Here is what my files look like

.env
```
AWS_ACCESS_KEY_ID=XXXXX
AWS_SECRET_ACCESS_KEY=XXXXX
AWS_DEFAULT_REGION=ap-south-1
AWS_BUCKET=XXXX
AWS_URL=https://XXXX.cloudfront.net/
AWS_ACCESS_URL_PREFIX=https://XXXX.s3.ap-south-1.amazonaws.com/
CLOUDFRONT_KEY_PAIR_ID=XXXXX
CLOUDFRONT_PRIVATE_KEY_PATH=pk-XXXX.pem
```

filesystems.php
```
's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],
```

display image blade file
`<a href="app-list.html"><img src="{{CloudFrontUrlSigner::sign(env('AWS_ACCESS_URL_PREFIX').$project->creator->company_slug.'/'.$project->icon)}}"></a>`

**Comment by cypherinc** [comment]
@michaellwatson @owenconti I tried to load the image using Storage facade as below

`<a href="app-list.html"><img src="{{CloudFrontUrlSigner::sign(Storage::disk('s3')->url(env('AWS_ACCESS_URL_PREFIX').$project->creator->company_slug.'/'.$project->icon))}}"></a>`

now getting Access Denied error

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3504D7DE3EFA2C85</RequestId>
<HostId>74U/KL2qTjPS8dEkntij4lKl2Om7mqIbZwAkJijb1MGREz+vPN/EoBBPXIok9UedcI1m1z5He4Q=</HostId>
</Error>
```

**Comment by michaellwatson** [comment]
@cypherinc you're calling the signer on the S3 url, try it on the AWS_URL path instead

**Comment by cypherinc** [comment]
It turned out that I didn't the AWS_ACCESS_URL_PREFIX while accessing the file, below code worked like a charm

`<a href="app-list.html"><img src="{{CloudFrontUrlSigner::sign(Storage::disk('s3')->url($project->creator->company_slug.'/'.$project->icon))}}"></a>`

Thanks a lot @owenconti  @michaellwatson
