### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by jdssem** [dreamonkey/laravel-cloudfront-url-signer#6]
Laravel 5.8 had been released. Could your support 5.8 version?
Thanks.

**Comment by IlCallo** [comment]
Hi, our company is not using the package in our projects with Laravel more than 5.7, but if you want to try a PR, we can merge it :)

**Comment by silasrm** [comment]
https://github.com/dreamonkey/laravel-cloudfront-url-signer/pull/7

**Comment by IlCallo** [comment]
Solved by https://github.com/dreamonkey/laravel-cloudfront-url-signer/pull/8 and released as 2.1.0.
Tell me if there are any problems ;)
